// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Districts{
  districtKey varchar [not null, pk, unique]
  districtCode varchar
  districtName varchar
}

Table TeamInfo {
  teamKey integer  [not null, pk , unique]
  teamNumber integer
  nameFull varchar
  nameShort varchar
  districtKey varchar [ref: > Districts.districtKey]
  rookieYear integer
  city varchar
  stateProv varchar
  country varchar
}


Table Events {
  eventKey varchar [not null, pk , unique]
  year integer [not null]
  event varchar
  eventType varchar 
  date date
  location varchar
  Webcast varchar
  weekNumber integer
  districtKey varchar [ref: > Districts.districtKey]
}


Table MatchTable {
  matchKey varchar [not null, pk, unique ]
  eventKey varchar [not null, ref: > Events.eventKey]
  year integer
  matchLevel varchar
}


Table MatchTeams {
  matchKey integer [not null, ref: > MatchTable.matchKey]
  teamKey integer [not null, ref: > TeamInfo.teamKey ]
  alliance varchar [not null]
  
  indexes {
    (matchKey, teamKey) [pk, unique] // composite PK
  }
}


Table MatchData2026 {
  matchKey integer [ not null, ref: > MatchTable.matchKey]
  alliance integer  [not null]
  totalScore  integer
  teleopCount integer
  autoScore integer
  shift1Points integer
  shift2Points integer
  shift3Points integer
  shift4Points integer
  endgamePoints integer
  autoTowerPoints integer
  totalAutoPoints integer
  endgameTowerPoints integer
  totalTowerPoints integer
  minorFoulCount integer
  majorFoulCount integer
  foulPoints integer
  adjustPoins integer
  RP integer

  indexes {
    (matchKey, alliance) [pk, unique] //composite pk
  }
}





